"""remove status

Revision ID: 0bb5e4016f31
Revises: 758be8e8b668
Create Date: 2023-06-02 12:50:47.641398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bb5e4016f31'
down_revision = '758be8e8b668'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backups', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backups', sa.Column('status', postgresql.ENUM('scheduled', 'running', 'finished', 'failed', name='backupstatus'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
