"""rename field

Revision ID: b2723b264955
Revises: a50c987b7a3f
Create Date: 2023-06-01 14:46:40.140468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2723b264955'
down_revision = 'a50c987b7a3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'running', 'finished', 'failed', name='backupstatus'), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('backups', sa.Column('rrule', sa.String(), nullable=True))
    op.drop_column('backups', 'rrulestring')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backups', sa.Column('rrulestring', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('backups', 'rrule')
    op.drop_table('backup_records')
    # ### end Alembic commands ###
